id: I8487859F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T08:46:52+00:00'
last_modified: '2022-06-08T07:33:54.253125+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ1854
  title: རྡོ་རྗེ་གླིང་པའི་ཟབ་གཏེར་རྣམས་དང་མཇལ་བའི་གཏེར་བྱང་རྣམ་ཐར་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    7DA8:
      image_group_id: I1CZ1906
      title: ''
      total_pages: 122
      order: 1
      base_file: 7DA8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
