id: I8487859F
legacy_id: P006884
ocr_import_info:
  bdrc_scan_id: W1CZ1854
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T08:46:06'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T19:05:05.940045+00:00'
last_modified: 2022-08-31 03:05:17.970990
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1CZ1854
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1CZ1854
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྡོ་རྗེ་གླིང་པའི་ཟབ་གཏེར་རྣམས་དང་མཇལ་བའི་གཏེར་བྱང་རྣམ་ཐར།
  author: རྡོ་རྗེ་གླིང་པ།
statistics:
  ocr_word_mean_confidence_index: 0.4339957180025825
  ocr_word_median_confidence_index: 0.3499999940395355
quality: null
bases:
  I1CZ1906:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ1906
      total_pages: 122
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ1906.txt
    statistics:
      ocr_word_median_confidence_index: 0.3499999940395355
      ocr_word_mean_confidence_index: 0.4339957180025825
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
